<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>UncomplicatedCustomBots</RootNamespace>
    <AssemblyName>UncomplicatedCustomBots</AssemblyName>
    <LangVersion>14</LangVersion>
    <Deterministic>true</Deterministic>
    <OutputType>Library</OutputType>
    <FileAlignment>512</FileAlignment>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Configurations>LabApi;LabApi-Debug;Exiled;Exiled-Debug</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'LabApi' ">
    <DefineConstants>LABAPI</DefineConstants>
    <AssemblyName>UncomplicatedCustomBots-LabApi</AssemblyName>
    <OutputPath>bin\LabAPI\</OutputPath>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Exiled' ">
    <DefineConstants>EXILED</DefineConstants>
    <AssemblyName>UncomplicatedCustomBots-Exiled</AssemblyName>
    <OutputPath>bin\Exiled\</OutputPath>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'LabApi-Debug' ">
    <DefineConstants>LABAPI;DEBUG;TRACE</DefineConstants>
    <AssemblyName>UncomplicatedCustomBots-LabApi</AssemblyName>
    <OutputPath>bin\LabAPI-Debug\</OutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Exiled-Debug' ">
    <DefineConstants>EXILED;DEBUG;TRACE</DefineConstants>
    <AssemblyName>UncomplicatedCustomBots-Exiled</AssemblyName>
    <OutputPath>bin\Exiled-Debug\</OutputPath>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <Optimize>false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\ExportedMeshes.bin" />
  </ItemGroup>

  <ItemGroup>
    <!--SL References-->
    <Reference Include="Assembly-CSharp" Publicize="true" HintPath="$(SL_REFERENCES)/Assembly-CSharp.dll" />
    <Reference Include="Assembly-CSharp-firstpass" Publicize="true" HintPath="$(SL_REFERENCES)/Assembly-CSharp-firstpass.dll" />
    <Reference Include="CommandSystem.Core" HintPath="$(SL_REFERENCES)/CommandSystem.Core.dll" />
    <Reference Include="Pooling" HintPath="$(SL_REFERENCES)/Pooling.dll" />
    <Reference Include="Mirror" Publicize="true" HintPath="$(SL_REFERENCES)/Mirror.dll" />
    <Reference Include="Mirror.Components" Publicize="true" HintPath="$(SL_REFERENCES)/Mirror.Components.dll" />
    <Reference Include="NorthwoodLib" Publicize="true" HintPath="$(SL_REFERENCES)/NorthwoodLib.dll" />
    <Reference Include="System.IO.Compression" HintPath="$(SL_REFERENCES)/System.IO.Compression.dll" />
    <Reference Include="YamlDotNet" HintPath="$(SL_REFERENCES)/YamlDotNet.dll" />

    <Reference Include="UnityEngine" HintPath="$(SL_REFERENCES)/UnityEngine.dll" />
    <Reference Include="UnityEngine.AIModule" HintPath="$(SL_REFERENCES)/UnityEngine.AIModule.dll" />
    <Reference Include="UnityEngine.AnimationModule" HintPath="$(SL_REFERENCES)/UnityEngine.AnimationModule.dll" />
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(SL_REFERENCES)/UnityEngine.AssetBundleModule.dll" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(SL_REFERENCES)/UnityEngine.CoreModule.dll" />
    <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(SL_REFERENCES)/UnityEngine.JSONSerializeModule.dll" />
    <Reference Include="UnityEngine.PhysicsModule" HintPath="$(SL_REFERENCES)/UnityEngine.PhysicsModule.dll" />
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(SL_REFERENCES)/UnityEngine.UnityWebRequestModule.dll" />
    <Reference Include="UnityEngine.UnityWebRequestWWWModule" HintPath="$(SL_REFERENCES)/UnityEngine.UnityWebRequestWWWModule.dll" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" Condition=" '$(Configuration)' == 'Exiled' Or '$(Configuration)' == 'Exiled-Debug'" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
    <PackageReference Include="Northwood.LabAPI" Version="1.1.6.1" Publicize="true" />
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*" />
  </ItemGroup>

  <Target Name="PostBuildCopyExiledDll" AfterTargets="Build" Condition=" '$(Configuration)' == 'Exiled' ">
    <Message Text="Copying UncomplicatedCustomBots-Exiled.dll to EXILED plugin folder..." Importance="high" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomBots-Exiled.dll" DestinationFolder="$(APPDATA)\EXILED\Plugins" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="PostBuildCopyLabApiDll" AfterTargets="Build" Condition=" '$(Configuration)' == 'LabApi' ">
    <Message Text="Copying UncomplicatedCustomBots-LabApi.dll to LabAPI plugin folder..." Importance="high" />
    <Copy SourceFiles="$(OutputPath)UncomplicatedCustomBots-LabApi.dll" DestinationFolder="$(APPDATA)\SCP Secret Laboratory\LabAPI\plugins\global" SkipUnchangedFiles="true" />
  </Target>

</Project>
